name: PR Labeler
on:
  pull_request:
    types: [opened]

permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/pr-labeler-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
